### PR TITLE
add wasm-strip to reduce size even more 

### PR DESCRIPTION
**Pull request by tyshko-rostyslav**
Closes: #135

### CODE REVIEW

**Comment by rymnc** [comment]
Should wasm-strip be added to the deps in the Makefile?
You can add the post-build task to the dependency array https://github.com/vacp2p/zerokit/blob/658d07ae8cd7148a7d7a8237d2400bd88c7a7abf/rln-wasm/Makefile.toml#L8-L14 so that it runs automatically

**Comment by tyshko-rostyslav** [comment]
> Should wasm-strip be added to the deps in the Makefile? You can add the post-build task to the dependency array
> 
> https://github.com/vacp2p/zerokit/blob/658d07ae8cd7148a7d7a8237d2400bd88c7a7abf/rln-wasm/Makefile.toml#L8-L14
> 
> so that it runs automatically

wasm-strip, cannot be a dependency of `build`, since it needs a built `.wasm` file to work with first.

**Comment by rymnc** [comment]
pack-rename runs after the file is built, isn't it?

**Comment by tyshko-rostyslav** [comment]
> The error in CI is because wasm-strip isn't installed, please install it as a dependency in the root Makefile

I think it cannot find the file

**Comment by rymnc** [comment]
With this -
```
[tasks.post-build]
script = "wasm-strip pkg/rln_wasm_bg.wasm"
```
This is the build error -
```
[cargo-make] INFO - Running Task: pack-rename
[cargo-make] INFO - Running Task: post-build
/var/folders/v_/4f04x6_901qckppx8f0lj_h00000gn/T/fsio_E3zqzGVGzp.sh: line 3: wasm-strip: command not found
[cargo-make] ERROR - Error while executing command, exit code: 127
```

**Comment by tyshko-rostyslav** [comment]
> The "file" it cannot find is actually the executable for wasm-strip

Fixed

**Pull request merged**
