### PR TITLE
move to uncompressed versions

### PR DESCRIPTION
**Pull request by tyshko-rostyslav**

### CODE REVIEW

**Comment by rymnc** [comment]
@tyshko-rostyslav can we rebase this pr to master?

**Comment by rymnc** [comment]
@tyshko-rostyslav curious, why was this closed?

**Comment by richard-ramos** [comment]
Sure! i'll have a look now

**Comment by richard-ramos** [comment]
I'm getting results similar to these for executing [this test](https://github.com/waku-org/js-rln/blob/master/src/index.spec.ts#L6-L60), with almost all of that time spent generating the proof.
```
 Executed 1 of 1 SUCCESS (20.142 secs / 20.127 secs)
```

**Pull request closed without merging**
