### PR TITLE
feat(rln): add example usage tutorial and expand documentation for RLN

### PR DESCRIPTION
**Pull request by s1fr0**
This PR partially addresses https://github.com/vacp2p/zerokit/issues/69.

Items completed 
- [x] Basic documentation for how to use RLN in Zerokit.
- [x] Document `public` crate APIs documentation so that meaningful info appears when running `cargo doc`

---
In order to minimize the cognitive overhead given by following the tutorial proposed in first item, further APIs might be added in parallel PRs with the goal to minimize the amount of code required (e.g. simplify serialization, etc). Such effort will ease the understanding and design of a CLI interface as requested by https://github.com/vacp2p/zerokit/issues/70.

At the moment, such parallel PRs consist of:
- https://github.com/vacp2p/zerokit/pull/75

Merging/closing them PRs is a prerequisite for this one to be merged.

### CODE REVIEW

**Comment by oskarth** [comment]
Thanks! Do you think we can get this merged this week?

**Comment by oskarth** [comment]
Can we do the minimal needed to get this merged to master please?

cargo doc can be done separately, as well as other crates.

**Review by rymnc — APPROVED** [review]
LGTM

**Comment by oskarth** [comment]
Oh sorry I thought I reviewed this! Must've forgot to click button 😞

**Pull request merged**
